### ISSUE TITLE
undefined reference to `TGLGetMaximumContextVersion'

### ISSUE THREAD

**Issue by tdolphin-org** [BeWorld2018/SDL#7]
MorphOS 3.18, SDL 2.30.7

**/System/Development/gg/bin/../lib/gcc-lib/ppc-morphos/9.5.0/../../../../ppc-morphos/bin/ld: /usr/local/lib/libSDL2.a(sdl-startup.o): in function `__CSTP_init_SDL2Base':
sdl-startup.c:(.text+0x672): undefined reference to `TGLGetMaximumContextVersion'
/System/Development/gg/bin/../lib/gcc-lib/ppc-morphos/9.5.0/../../../../ppc-morphos/bin/ld: sdl-startup.c:(.text+0x682): undefined reference to `TGLGetMaximumContextVersion'**

for previous version 2.30.5 is ok

**Comment by BeWorld2018** [comment]
You need to add -lGL now with -lSDL2 (New TinyGL SDK)

**Comment by tdolphin-org** [comment]
> You need to add -lGL now with -lSDL2 (New TinyGL SDK)

But this error appear when I am using those options.

`g++ opengl_example.cpp -std=c++17 -Igg:/usr/local/include -noixemul -Lgg:/usr/local/lib -Lgg:/ppc-morphos/lib/libnix -lSDL2 -lGL -lc -lm`
