### ISSUE TITLE
Lite-xl keyboard shortcuts do not work with 2.30.9 release

### ISSUE THREAD

**Issue by walkero-gr** [BeWorld2018/SDL#8]
Hello there. It was reported to me and I managed to reproduce it, that keyboard shortcuts are not working on lite-xl 2.1.4r1 (https://www.morphos-storage.net/?id=2136323) with the latest SDL 2.30.9. Shortcuts like CTRL+SHIFT+P or CTRL+SHIFT+C should work when the application starts.

I tested all the releases between 2.30.0 and 2.30.9 and all worked fine except the latest one. So, something between 2.30.7 and 2.30.9 broke the keyboard shortcuts.

**Comment by BeWorld2018** [comment]
Sorry for late response :-)

i think it's relate to this new line: https://github.com/BeWorld2018/SDL/blob/SDL-2.30.9-release/src/video/morphos/SDL_moskeyboard.c#L81

i fix that for next release: https://github.com/BeWorld2018/SDL/commit/5e7a0364441c16cff03ffb35d3a998ff8bae53bb
